### ISSUE TITLE
网页打开后是灰白色？

### ISSUE THREAD

**Issue by MrQf1** [dribble-njr/glTF-Viewer-for-BIM#1]
程序编译后网页灰白色报错：Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0；将模型改动至public文件后报错：Uncaught (in promise) Error: THREE.GLTFLoader: No DRACOLoader instance provided.；根据内容添加dracoloader模块后该报错消失，模块儿路径在public下，运行后网页无报错，但是仍然是灰白色。求教！

**Comment by Stephen-wzw** [comment]
有可能是模型位置不对，所以没有显示出来，你可以调整一下位置、模型大小等试试。

**Comment by zeevenn** [comment]
你的模型应该是用了 Draco 压缩的，我的代码参考 gltf-viewer 重构了一下，减少了一些不需要的代码，可以再试试。
